"""
blocking/engine.py — BlockingEngine: orchestrates blocking strategies.

Responsibilities:
1. Accept a configurable list of BlockingStrategy objects.
2. Run each strategy over the country-partitioned source DataFrames.
3. Union all candidate outputs and deduplicate (source1_id, other_id) pairs
   while retaining which strategies contributed each pair (for diagnostics).
4. Filter degenerate candidates (from empty/too-short normalization keys).
5. Cap candidates per (source1_entity_id) to bound memory and compute.
6. Log oversized-block warnings.
7. Compute and return a diagnostics report: per-strategy candidate counts,
   per-strategy recall against ground truth (when available), combined recall,
   recall-after-cap.

Country partitioning happens UPSTREAM of this engine (callers split by country
before calling run()), so the engine itself is country-agnostic.
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass, field
from typing import Optional

import pandas as pd

from business_entity_resolution.blocking.base import BlockingStrategy

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Diagnostics report dataclass
# ---------------------------------------------------------------------------


@dataclass
class StrategyDiagnostic:
    """Per-strategy diagnostic information."""
    strategy_name: str
    raw_candidates: int
    unique_pairs: int
    recall: Optional[float] = None     # fraction of GT pairs captured; None if GT not provided


@dataclass
class BlockingDiagnostics:
    """Full diagnostic report from one BlockingEngine.run() call."""
    per_strategy: list[StrategyDiagnostic] = field(default_factory=list)
    total_candidates_before_cap: int = 0
    total_candidates_after_cap: int = 0
    blocking_recall_ceiling: Optional[float] = None  # combined recall before cap
    recall_after_cap: Optional[float] = None          # recall after candidate cap
    oversized_blocks_skipped: int = 0
    elapsed_seconds: float = 0.0

    def print_summary(self, prefix: str = "") -> None:
        """Print a human-readable diagnostics summary."""
        p = prefix
        print(f"\n{p}{'=' * 60}")
        print(f"{p}BLOCKING DIAGNOSTICS")
        print(f"{p}{'=' * 60}")
        print(f"{p}  Elapsed: {self.elapsed_seconds:.1f}s")
        print(f"{p}  Oversized blocks skipped: {self.oversized_blocks_skipped:,}")
        print(f"{p}  Total candidates (pre-cap):  {self.total_candidates_before_cap:,}")
        print(f"{p}  Total candidates (post-cap): {self.total_candidates_after_cap:,}")

        if self.blocking_recall_ceiling is not None:
            print(f"{p}  *** Blocking recall ceiling (pre-cap):  {self.blocking_recall_ceiling:.4f} ***")
        if self.recall_after_cap is not None:
            print(f"{p}  *** Recall after candidate cap:         {self.recall_after_cap:.4f} ***")

        print(f"\n{p}  Per-strategy breakdown:")
        for s in self.per_strategy:
            recall_str = f"  recall={s.recall:.4f}" if s.recall is not None else ""
            print(f"{p}    {s.strategy_name:<25} raw={s.raw_candidates:>8,}  "
                  f"unique={s.unique_pairs:>8,}{recall_str}")
        print(f"{p}{'=' * 60}\n")


# ---------------------------------------------------------------------------
# Engine
# ---------------------------------------------------------------------------


class BlockingEngine:
    """
    Orchestrates a configurable list of blocking strategies, unions their
    outputs, deduplicates, caps per-entity candidates, and reports diagnostics.

    Usage
    -----
    .. code-block:: python

        engine = BlockingEngine(strategies=[...], candidate_cap=30, max_block_size=500)
        candidates, diagnostics = engine.run(source1_df, other_df, ground_truth_df=gt)
    """

    def __init__(
        self,
        strategies: list[BlockingStrategy],
        candidate_cap: int = 30,
        max_block_size: int = 500,
        min_key_length: int = 2,
    ) -> None:
        """
        Parameters
        ----------
        strategies:
            Ordered list of BlockingStrategy instances.  All are run; their
            outputs are unioned.
        candidate_cap:
            Maximum candidate pairs per Source-1 entity (after all strategies).
            Excess candidates are dropped (those generated by later strategies
            in the list are dropped first, so strategy order implicitly sets priority).
        max_block_size:
            Maximum number of records in any single blocking key's block.
            Blocks larger than this are skipped to prevent runaway computation
            from degenerate normalization keys.
        min_key_length:
            Passed to strategies for reference; enforcement is per-strategy.
        """
        self._strategies = strategies
        self._candidate_cap = candidate_cap
        self._max_block_size = max_block_size
        self._min_key_length = min_key_length

    def run(
        self,
        source1_df: pd.DataFrame,
        other_df: pd.DataFrame,
        ground_truth_df: Optional[pd.DataFrame] = None,
        source_tag: str = "source2",
    ) -> tuple[pd.DataFrame, BlockingDiagnostics]:
        """
        Run all strategies, union and deduplicate results, apply candidate cap.

        Parameters
        ----------
        source1_df:
            Source-1 records (already normalised, country-partitioned).
        other_df:
            Source-2 or Source-3 records (same country partition).
        ground_truth_df:
            Optional ground truth DataFrame with columns (source1_entity_id,
            source_id, source_tag).  If provided, recall metrics are computed.
        source_tag:
            "source2" or "source3" — used to filter ground_truth_df.

        Returns
        -------
        tuple[pd.DataFrame, BlockingDiagnostics]
            - candidates: DataFrame(source1_entity_id, other_entity_id, strategy_name)
            - diagnostics: BlockingDiagnostics report
        """
        t0 = time.time()
        diagnostics = BlockingDiagnostics()

        # Build ground-truth set for recall computation (if available)
        gt_pairs: Optional[set[tuple[str, str]]] = None
        if ground_truth_df is not None and not ground_truth_df.empty:
            gt_filtered = ground_truth_df[ground_truth_df["source_tag"] == source_tag]
            gt_pairs = set(
                zip(gt_filtered["source1_entity_id"], gt_filtered["source_id"])
            )

        all_candidates: list[pd.DataFrame] = []

        for strategy in self._strategies:
            logger.info("Running blocking strategy: %s", strategy.name)
            t_strat = time.time()
            try:
                cands = strategy.generate_candidates(source1_df, other_df)
            except Exception:
                logger.exception("Strategy %s failed, skipping", strategy.name)
                cands = strategy._empty_candidates()

            raw_count = len(cands)

            # Deduplicate within strategy
            if not cands.empty:
                cands = cands.drop_duplicates(
                    subset=["source1_entity_id", "other_entity_id"]
                )

            unique_count = len(cands)

            # Per-strategy recall
            strategy_recall: Optional[float] = None
            if gt_pairs is not None and not cands.empty:
                cand_pairs = set(zip(cands["source1_entity_id"], cands["other_entity_id"]))
                hits = len(gt_pairs & cand_pairs)
                strategy_recall = hits / len(gt_pairs) if gt_pairs else 0.0

            diagnostics.per_strategy.append(StrategyDiagnostic(
                strategy_name=strategy.name,
                raw_candidates=raw_count,
                unique_pairs=unique_count,
                recall=strategy_recall,
            ))

            logger.info(
                "Strategy %s: %d raw -> %d unique candidates in %.1fs",
                strategy.name, raw_count, unique_count, time.time() - t_strat,
            )

            if not cands.empty:
                all_candidates.append(cands)

        # Union all strategy outputs
        if not all_candidates:
            logger.warning("All blocking strategies produced zero candidates.")
            diagnostics.elapsed_seconds = time.time() - t0
            return pd.DataFrame(
                columns=["source1_entity_id", "other_entity_id", "strategy_name"]
            ), diagnostics

        combined = pd.concat(all_candidates, ignore_index=True)

        # Global deduplication — keep the first (highest-priority) strategy's row
        # for each (source1_entity_id, other_entity_id) pair
        combined = combined.drop_duplicates(
            subset=["source1_entity_id", "other_entity_id"],
            keep="first",
        )

        diagnostics.total_candidates_before_cap = len(combined)

        # Blocking recall ceiling (before cap)
        if gt_pairs is not None:
            cand_pairs = set(zip(combined["source1_entity_id"], combined["other_entity_id"]))
            hits_before = len(gt_pairs & cand_pairs)
            diagnostics.blocking_recall_ceiling = (
                hits_before / len(gt_pairs) if gt_pairs else 0.0
            )

        # Apply candidate cap per Source-1 entity
        combined = self._apply_cap(combined, diagnostics)

        # Recall after cap
        if gt_pairs is not None:
            cand_pairs_capped = set(
                zip(combined["source1_entity_id"], combined["other_entity_id"])
            )
            hits_after = len(gt_pairs & cand_pairs_capped)
            diagnostics.recall_after_cap = hits_after / len(gt_pairs) if gt_pairs else 0.0

            discarded = (diagnostics.blocking_recall_ceiling or 0.0) - (diagnostics.recall_after_cap or 0.0)
            if discarded > 0.001:
                logger.warning(
                    "Candidate cap discarded %.4f recall (%d GT pairs lost). "
                    "Consider increasing candidate_cap.",
                    discarded,
                    int(discarded * len(gt_pairs)),
                )

        diagnostics.total_candidates_after_cap = len(combined)
        diagnostics.elapsed_seconds = time.time() - t0

        logger.info(
            "Blocking complete: %d candidates (cap reduced %d -> %d) in %.1fs",
            len(combined),
            diagnostics.total_candidates_before_cap,
            diagnostics.total_candidates_after_cap,
            diagnostics.elapsed_seconds,
        )

        return combined, diagnostics

    def _apply_cap(
        self,
        candidates: pd.DataFrame,
        diagnostics: BlockingDiagnostics,
    ) -> pd.DataFrame:
        """
        Keep at most *candidate_cap* rows per Source-1 entity.

        Strategy-name ordering is preserved (earlier strategies have implicit
        priority since we deduplicated keeping "first" above).
        """
        if self._candidate_cap <= 0:
            return candidates

        counts = candidates.groupby("source1_entity_id").cumcount()
        return candidates[counts < self._candidate_cap].copy()
